sudo: false
language: node_js

branches:
  only:
    - master

matrix:
  fast_finish: true

node_js:
  - 'node'
  - '8'
  - '6'
  - '4'

os:
  - linux
  - osx

script:
  - npm run build
  - npm run smoke
